spring:
  profiles:
    active: dev
broad:
  sign:
    use-header: true
    header-key: broad-x-token
    expire-in-seconds: 300
    algorithm: MD5
  #cache:
  #  type: redis
  #  redis:
  #    ip: 127.0.0.1
  #    port: 16379
  #    password: SbtyMveYNfLzTks7H0apCmyStPzWJqje
